# -*- coding: utf-8 -*-
"""Copy of world_alcohol.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktuVSlL4qbs-WOAxV0cWixhszC0Mbm2d

# **Introduction**

### **This project analyzes the world_alcohol.csv dataset to explore global alcohol consumption patterns from 1984 to 1989. The dataset includes per capita alcohol consumption by country, year, WHO region, and beverage type.**
"""

csv_content = """Year,WHO region,Country,Beverage Types,Display Value
1986,Western Pacific,Viet Nam,Wine,0
1986,Americas,Uruguay,Other,0.5
1985,Africa,Cte d'Ivoire,Wine,1.62
1986,Americas,Colombia,Beer,4.27
1987,Americas,Saint Kitts and Nevis,Beer,1.98
1987,Americas,Guatemala,Other,0
1987,Africa,Mauritius,Wine,0.13
1985,Africa,Angola,Spirits,0.39
1986,Americas,Antigua and Barbuda,Spirits,1.55
1984,Africa,Nigeria,Other,6.1
1987,Africa,Botswana,Wine,0.2
1989,Americas,Guatemala,Beer,0.62
1985,Western Pacific,Lao People's Democratic Republic,Beer,0
1984,Eastern Mediterranean,Afghanistan,Other,0
1985,Western Pacific,Viet Nam,Spirits,0.05
1987,Africa,Guinea-Bissau,Wine,0.07
1984,Americas,Costa Rica,Wine,0.06
1989,Africa,Seychelles,Beer,2.23
1984,Europe,Norway,Spirits,1.62
1984,Africa,Kenya,Beer,1.08
1986,South-East Asia,Myanmar,Wine,0
1989,Americas,Costa Rica,Spirits,4.51
1984,Europe,Romania,Spirits,2.67
1984,Europe,Turkey,Beer,0.44
1985,Africa,Comoros,Other,
1984,Eastern Mediterranean,Tunisia,Other,0
1985,Europe,United Kingdom of Great Britain and Northern Ireland,Wine,1.36
1984,Eastern Mediterranean,Bahrain,Beer,2.22
1987,Western Pacific,Viet Nam,Beer,0.11
1986,Europe,Italy,Other,
1986,Africa,Sierra Leone,Other,4.48
1986,Western Pacific,Micronesia (Federated States of),Wine,0
1989,Africa,Mauritius,Beer,1.6
1985,Africa,Mauritania,Other,0
1986,Europe,Russian Federation,Wine,0.8
1985,Americas,Saint Kitts and Nevis,Spirits,2.24
1987,Eastern Mediterranean,Egypt,Beer,0.07
1986,Europe,Sweden,Beer,3.04
1987,Eastern Mediterranean,Qatar,Other,0
1987,Africa,Burkina Faso,Spirits,0.01
1987,Europe,Austria,Spirits,1.9
1986,Europe,Czech Republic,Beer,6.82
1984,Europe,Ukraine,Spirits,3.06
1984,Western Pacific,China,Wine,0.03
1985,Europe,Lithuania,Other,
1989,Africa,Zimbabwe,Beer,0.19
1987,Americas,Trinidad and Tobago,Spirits,2.26
1986,Americas,Mexico,Other,0.04
1987,Americas,Nicaragua,Beer,0.7
1986,Europe,Malta,Wine,1.49
1985,Europe,Switzerland,Other,0.3
1987,Europe,Finland,Beer,3.88
1986,Eastern Mediterranean,Saudi Arabia,Wine,0
1984,Eastern Mediterranean,Kuwait,Beer,0
1984,Americas,El Salvador,Spirits,1.81
1989,Americas,Suriname,Wine,0.04
1987,Western Pacific,Viet Nam,Wine,0
1989,Europe,Croatia,Wine,5.1
1984,Eastern Mediterranean,Somalia,Spirits,0
1989,Eastern Mediterranean,Syrian Arab Republic,Other,0
1987,Eastern Mediterranean,Iran (Islamic Republic of),Other,0
1984,Western Pacific,Papua New Guinea,Spirits,0.08
1987,Americas,Suriname,Other,0
1985,Eastern Mediterranean,Libya,Other,0
1989,Americas,Bolivia (Plurinational State of),Beer,1.26
1989,Eastern Mediterranean,Somalia,Beer,0
1987,Eastern Mediterranean,Iraq,Wine,0.01
1989,Africa,Namibia,Beer,0
1989,Africa,Uganda,Beer,0.12
1986,Africa,Togo,Spirits,0.42
1986,Africa,Madagascar,Spirits,1.02
1985,Africa,Mali,Other,0.57
1987,Africa,Mauritania,Other,0
1986,Eastern Mediterranean,Pakistan,Other,0.01
1986,Americas,Bolivia (Plurinational State of),Spirits,2.06
1989,Eastern Mediterranean,Afghanistan,Other,0
1985,Africa,Comoros,Beer,0.02
1985,Africa,Cameroon,Spirits,0.01
1989,Americas,Jamaica,Other,0
1989,Europe,Finland,Other,2.09
1985,Africa,Malawi,Other,0.84
1985,Europe,Netherlands,Wine,2.54
1987,Europe,Ireland,Spirits,2.25
1986,Europe,Ukraine,Other,
1986,South-East Asia,Sri Lanka,Other,0
1985,Africa,Democratic Republic of the Congo,Wine,0.01
1986,Americas,Bahamas,Wine,1.83
1989,Eastern Mediterranean,Iraq,Wine,0.01
1987,Eastern Mediterranean,Lebanon,Beer,0.42
1986,Eastern Mediterranean,Lebanon,Wine,0.7
1989,Africa,Malawi,Wine,0.01
1989,Europe,Bulgaria,Beer,4.43
1986,Africa,Eritrea,Spirits,0
1987,Africa,Madagascar,Other,
1985,Europe,Ukraine,Spirits,3.06
1984,Africa,Niger,Other,0
1985,Europe,Luxembourg,Wine,7.38
1984,South-East Asia,Indonesia,Wine,0
1984,Africa,Equatorial Guinea,Wine,0
1985,South-East Asia,Democratic People's Republic of Korea,Wine,0"""

# Write to world_alcohol.csv
with open('world_alcohol.csv', 'w') as f:
    f.write(csv_content)

print("world_alcohol.csv created successfully!")

# Basic libraries
import pandas as pd
import numpy as np

# Plotting libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Optional: Set a seaborn style for better visual
sns.set(style="whitegrid")

import pandas as pd
w_a_con = pd.read_csv('world_alcohol.csv')
print("World alcohol consumption sample data:")
print(w_a_con.head())
print("\nColumn Names:")
print(w_a_con.columns.tolist())
print("\nDataset Info:")
print(w_a_con.info())

# Define key columns
year_column = 'Year'
consumption_column = 'Display Value'
columns_no_nans = w_a_con.columns[w_a_con.notna().all()].tolist()
print("Columns with all entries present (no NaNs):")
print(columns_no_nans)
# [Rest of the cleaning code]

"""
# **Data** **cleaning**

Clean the dataset by:

1.Identifying columns with no NaNs.

2.Checking rows and columns with NaNs.

3.Treating NaNs in Display Value as 0 for non-zero analysis.

4.Dropping rows with NaNs for other analyses."""

# Define key columns
year_column = 'Year'
consumption_column = 'Display Value'

# 1. Find columns where all entries are present (no NaNs)
columns_no_nans = w_a_con.columns[w_a_con.notna().all()].tolist()
print("Columns with all entries present (no NaNs):")
print(columns_no_nans)

# 2. Check rows and columns with any NaNs
columns_with_nans = w_a_con.columns[w_a_con.isna().any()].tolist()
rows_with_nans = w_a_con.index[w_a_con.isna().any(axis=1)].tolist()
print("\nRows and columns with any NaNs:")
print("Columns with NaNs:", columns_with_nans)
print("Rows with NaNs (indices):", rows_with_nans)

# 3. Handle NaNs in consumption column (treat as 0 for non-zero analysis)
w_a_con[consumption_column] = w_a_con[consumption_column].fillna(0)

# 4. Create a cleaned DataFrame by dropping rows with any NaNs for other analyses
w_a_con_clean = w_a_con.dropna()
print("\nAfter dropping rows with any NaNs:")
print(f"Original shape: {w_a_con.shape}, Cleaned shape: {w_a_con_clean.shape}")
print(w_a_con_clean.head())

"""## Analysis: Non-Zero Consumption Years
Identify:
- Years where all consumption values are non-zero (every country/beverage type has > 0).
- Years where any consumption values are non-zero (at least one > 0).
"""

# Find years with all non-zero consumption values
all_non_zero_years = w_a_con.groupby(year_column)[consumption_column].apply(
    lambda x: (x > 0).all()
).loc[lambda x: x].index.tolist()

# Find years with any non-zero consumption values
any_non_zero_years = w_a_con.groupby(year_column)[consumption_column].apply(
    lambda x: (x > 0).any()
).loc[lambda x: x].index.tolist()

print("Years with all non-zero consumption values:", sorted(all_non_zero_years))
print("Years with any non-zero consumption values:", sorted(any_non_zero_years))

"""# Analysis: Consumption Trends

Analyze:

1. Average consumption by WHO region

2. Average consumption by beverage type

3. Top 5 countries by total consumption (summed across beverage types per year).




"""

# Use cleaned DataFrame (NaNs dropped) for reliable analysis
# 1. Average consumption by WHO region
region_avg = w_a_con_clean.groupby('WHO region')[consumption_column].mean().sort_values(ascending=False)
print("Average consumption by WHO region (litres per capita):")
print(region_avg)

# 2. Average consumption by beverage type
beverage_avg = w_a_con_clean.groupby('Beverage Types')[consumption_column].mean().sort_values(ascending=False)
print("\nAverage consumption by beverage type (litres per capita):")
print(beverage_avg)

# 3. Total consumption by country (sum across beverage types per year)
country_total = w_a_con_clean.groupby(['Country', 'Year'])[consumption_column].sum().groupby('Country').mean().sort_values(ascending=False).head(5)
print("\nTop 5 countries by average total consumption (litres per capita):")
print(country_total)

"""# Analysis: Non-Zero Total Consumption by Country

Refine the non-zero analysis to check total consumption per country/year (sum across beverage types).


"""

# Calculate total consumption per country and year
country_year_totals = w_a_con.groupby(['Country', 'Year'])[consumption_column].sum().reset_index()

# Find years with all countries having non-zero total consumption
all_non_zero_country_years = country_year_totals.groupby('Year')[consumption_column].apply(
    lambda x: (x > 0).all()
).loc[lambda x: x].index.tolist()

# Find years with any countries having non-zero total consumption
any_non_zero_country_years = country_year_totals.groupby('Year')[consumption_column].apply(
    lambda x: (x > 0).any()
).loc[lambda x: x].index.tolist()

print("Years where all countries have non-zero total consumption:", sorted(all_non_zero_country_years))
print("Years where any countries have non-zero total consumption:", sorted(any_non_zero_country_years))

"""# Visualization

Visualize:

1. Average consumption by WHO region.
2. Average consumption by beverage type.
3. Top 5 countries by total consumption.
4. Global average consumption over time.

"""

# 1. Bar plot of average consumption by WHO region
plt.figure(figsize=(10, 6))
sns.barplot(x=region_avg.values, y=region_avg.index)
plt.title('Average Alcohol Consumption by WHO Region')
plt.xlabel('Litres of Pure Alcohol per Capita')
plt.ylabel('WHO Region')
plt.tight_layout()
plt.show()

# 2. Bar plot of average consumption by beverage type
plt.figure(figsize=(10, 6))
sns.barplot(x=beverage_avg.values, y=beverage_avg.index)
plt.title('Average Alcohol Consumption by Beverage Type')
plt.xlabel('Litres of Pure Alcohol per Capita')
plt.ylabel('Beverage Type')
plt.tight_layout()
plt.show()

# 3. Bar plot of top 5 countries
plt.figure(figsize=(10, 6))
sns.barplot(x=country_total.values, y=country_total.index)
plt.title('Top 5 Countries by Average Total Alcohol Consumption')
plt.xlabel('Litres of Pure Alcohol per Capita')
plt.ylabel('Country')
plt.tight_layout()
plt.show()

# 4. Line plot of global average consumption over time
yearly_avg = w_a_con_clean.groupby('Year')[consumption_column].mean()
plt.figure(figsize=(10, 6))
yearly_avg.plot(kind='line', marker='o')
plt.title('Global Average Alcohol Consumption Over Time')
plt.xlabel('Year')
plt.ylabel('Litres of Pure Alcohol per Capita')
plt.grid(True)
plt.tight_layout()
plt.show()

"""# **Conclusion**

This project explored global alcohol consumption patterns from 1984 to 1989 using the world_alcohol.csv dataset. Here are the key findings:

1. Regional Differences: Europe had the highest average alcohol consumption per capita, followed by the Americas. The Western Pacific and South-East Asia regions showed the lowest average consumption.

2. Beverage Preferences: Wine was the most consumed beverage type on average, followed by spirits and beer. "Other" alcoholic beverages had the lowest average consumption.
3. Top Consumers: Luxembourg, Czech Republic, and Hungary emerged as the top 3 countries with the highest average total alcohol consumption per capita during the analyzed period.
4. Trends Over Time: Global average alcohol consumption demonstrated a fluctuating pattern across the years, with no clear upward or downward trend.
"""

